# -*- coding: utf-8 -*-
"""006_VISUALIZAÇÃO-DE-DADOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ErC3vQ6T2CUOjFTiGujXxnat8McZMbLt

# **VISUALIZAÇÃO DE DADOS**

Matplotlib site oficial: https://matplotlib.org
    Seaborn site oficial: https://seaborn.pydata.org
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# base de dados online
sns.get_dataset_names()

df = sns.load_dataset('iris')

# 150 linhas, 5 colunas
df.shape

df.info()

# acessar todas as espécies (valores únicos)
df.species.unique()

# gráfico de linhas - afirmações sobre a largura da petála e sua categoria
# ex. vendas por mês > linha do tempo

plt.figure(figsize=(15, 5))
plt.plot(df.index, df.petal_width, color='skyblue')
plt.title('Largura da Petála por Espécie')
plt.xlabel('Índice')
plt.ylabel('Largura (cm)')
plt.legend(['Largura da Pétala'])

# gráfico de linhas - 2 linhas

plt.figure(figsize=(12, 5))
plt.plot(df.index, df.petal_length, color='skyblue')
plt.plot(df.index, df.petal_width, color='pink', linewidth=1.8, ls='--')
plt.legend(['Comprimento', 'Largura'])

# gráfico de barras verticais
# ranking de coisas, ex. loja, vendedor, produto

plt.figure(figsize=(8, 6))
plt.barh(width=df.index, y=df.species, color='lightgreen');
plt.title('Quantidade de Espécies')
plt.legend(['Espécies'])
plt.xlabel('Quantidade')
plt.ylabel('Espécie')

# gráfico de barras horizontais
sns.barplot(data=df, x='petal_width', y=df.species)

# gráfico de pizza

df_contagem = df.species.value_counts()
df_contagem

plt.figure(figsize=(7, 15))
plt.pie(df_contagem, labels=df_contagem.values, explode=[0.1 , 0, 0]);
plt.legend(df_contagem.index)
plt.title('Gráfico de Pizza');

# mensurar vendas ficticias

# gráfico de dispersão
plt.scatter(x=df.petal_length, y=df.petal_width, color='skyblue');
